feat: Upgrade Text Reader Interaction
oat-sa/extension-pcisample pull request #110
Opened 2022-05-02 14:05 UTC by bartlomiejmarszal

In order to fix old PCI Text Reader image handling we created script that can be executed to create task for each Item that contain Text Reader PCI and modify an image handling.

2022-05-03 07:46 UTC, andreluizmachado requested changes

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +                            $queueName ?? $this->queueDispatcher->getDefaultQueue()->getName()
I'd go more strict by not giving the option to use the default queue, only a custom one.

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +                    break;
why do we have this break?

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            throw new Exception('Item payload has not been set');
Just to be sure. Can you confirm that these exceptions are being logged?

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            throw new Exception('Could not find a resouce with that uri');
Could you please also include the itemUri on the logs?

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +            $itemUri = $itemResource->getUri();
What if we just move this logic to the task? We can avoid to load the file from s3 twice, plus going to the DB as well.

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $dom->loadHTML($element);
Are we sure that is HTML?

2022-05-03 07:46 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $properties['content-' . $image['fileName']] = sprintf(
Shouldn't we sanitise `$image['fileName']`. Ex: `htmlspecialchars($image['fileName'], ENT_XML1)`

2022-05-03 08:01 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +                            $queueName ?? $this->queueDispatcher->getDefaultQueue()->getName()
Our worker, that is running, will execute all queues that he has. No matter if it will be in a custom queue. 
Another thing is that we do not have a easy way to create queue. Queue that we want to use, have to be created before programatically by migration. I could not found script that will allow this. 
Thos are the reason why I choose to leave this to default queue.

2022-05-03 08:04 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +                    break;
If we found 1 legacy PCI we want to create new task for an item no matter if there is more of those. This is responsibility of a task later. We **detected** item so we can create a task.

2022-05-03 08:28 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            throw new Exception('Could not find a resouce with that uri');
https://github.com/oat-sa/extension-pcisample/pull/110/commits/803b8a0b8fa2b8e675a6c6f2f4eb91e109a20b2d

2022-05-03 08:31 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $dom->loadHTML($element);
We are interested only about items that are part of html structure. In more precise `img` tag. If we will not recognise this tag it's means that interaction is not in our scope.

2022-05-03 08:33 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $properties['content-' . $image['fileName']] = sprintf(
If I sanitise I need to change this value also in place where it was called. If it was not yet sanitised before, then we can not do too much here.

2022-05-03 08:35 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/LegacyTextReaderItemUpdate.php
> +            $itemUri = $itemResource->getUri();
This is process of item detection that will create a task. I very much would like to pass this loaded content to task later but we cannot use objects as payload for tasks.

2022-05-03 14:47 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $properties['content-' . $image['fileName']] = sprintf(
My main concern here is:
filename: image<test.jpg
if we have an image with this name. Can we load this content again?

2022-05-03 16:01 UTC, bartlomiejmarszal commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $properties['content-' . $image['fileName']] = sprintf(
https://user-images.githubusercontent.com/16231681/166490655-e109b7a5-59ad-4b1a-97b5-95116e7e5c0c.mp4

2022-05-04 06:57 UTC, andreluizmachado commented on model/LegacyPciHelper/Task/UpgradeTextReaderInteractionTask.php
> +            $properties['content-' . $image['fileName']] = sprintf(
cool, so then we are good!

2022-05-04 08:29 UTC, andreluizmachado approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-05-04 11:25 UTC, pnal approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-05-04 11:37 UTC, merged