Fix/tr 6156/open links in a new tab text reader interaction
oat-sa/extension-pcisample pull request #164
Opened 2024-06-25 08:03 UTC by Nicholass

2024-06-25 09:26 UTC, oatymart requested changes
The code has a couple of mistakes but the principle is ok and I verified that after fixing, it will do its job well.

There are also a few extra things needed to complete the PR:
- Bump the versions in the 2 manifests: `dev/textReaderInteraction/pciCreator.json` and `ims/textReaderInteraction/imsPciCreator.json`
- When the code is approved, the minified files need to be added to the PR. The command is (in `tao/views/build`): `npx grunt portableelement -e=pciSamples -i=textReaderInteraction`
- A migration should be created to install the new version of the IMS PCI (1.2.2). See [this example](https://github.com/oat-sa/extension-pcisample/commit/beb36b2faabadf2806914d0999712f288ee7054d#diff-e7ff910511f98a5804547ead34deca30e9418cf4bc0b4cc35d21051f6bcc03c8) and be aware that there is a CLI for generating, running and rolling back the migrations ([documented here](https://oat-sa.atlassian.net/wiki/spaces/~456852655/pages/1408665016/Migrations+Example))

2024-06-25 09:26 UTC, oatymart commented on views/js/pciCreator/dev/textReaderInteraction/runtime/js/renderer.js
> +         * @returns {String} the html without updated URLs
```suggestion
         * @returns {String} the html with fixed anchor targets
```

2024-06-25 09:26 UTC, oatymart commented on views/js/pciCreator/ims/textReaderInteraction/runtime/js/renderer.js
> +                        anchors = selectorContainer.querySelectorAll('a');
This one needs `var anchors;`, above.

2024-06-25 09:26 UTC, oatymart commented on views/js/pciCreator/dev/textReaderInteraction/runtime/js/renderer.js
> +        var self = this;
Indentation

2024-06-25 09:32 UTC, oatymart commented
Please add PR description too. It's a must-have.

2024-06-27 12:43 UTC, Nicholass commented on views/js/pciCreator/dev/textReaderInteraction/runtime/js/renderer.js
> +                        );
now HTML fixes are performed consecutively

2024-06-27 12:44 UTC, Nicholass commented on views/js/pciCreator/dev/textReaderInteraction/runtime/js/renderer.js
> +         * @returns {String} the html without updated URLs
fixed docstring

2024-06-28 07:18 UTC, wazelin requested changes
In order for TAO 3.x to register the updated PCI runtime and creator code, the PCI must be registered via a migration.
See https://github.com/oat-sa/extension-pcisample/blob/beb36b2faabadf2806914d0999712f288ee7054d/migrations/Version202406120835514106_pciSamples.php as an example.

Such a migration can be added by running [this command](https://github.com/oat-sa/tao-core/blob/51d0c2e9fd1e273b250b30483f00fc99a292787f/scripts/tools/Migrations.php#L76), i.e. `docker exec nextgen_tao php index.php '\oat\tao\scripts\tools\Migrations' -c generate -e pciSamples`.

Be sure to _install_ the extension first if it hadn't been already: `docker exec nextgen_tao php tao/scripts/installExtension.php pciSamples`.

2024-07-03 07:55 UTC, oatymart commented on migrations/Version202407021254084106_pciSamples.php
> +  use oat\tao\scripts\tools\migrations\AbstractMigration;
```suggestion
  use Doctrine\DBAL\Schema\Schema;
  use Doctrine\Migrations\Exception\IrreversibleMigration;
  use oat\pciSamples\scripts\install\RegisterPciTextReaderIMS;
  use oat\tao\scripts\tools\migrations\AbstractMigration;
```
You need to `use` all classes you reference in the script, or the migration will error.

2024-07-03 07:57 UTC, oatymart commented on migrations/Version202407021254084106_pciSamples.php
Please check the file indentation against previous PHP files. I think it is all indented by 2 spaces too much.

2024-07-03 07:59 UTC, oatymart requested changes
Please test your migration:
Up:
`docker exec nextgen_tao php index.php '\oat\tao\scripts\tools\Migrations' -c execute -v 'oat\pciSamples\migrations\Version202407021254084106_pciSamples'`
Down:
`docker exec nextgen_tao php index.php '\oat\tao\scripts\tools\Migrations' -c rollback -v 'oat\pciSamples\migrations\Version202407021254084106_pciSamples'`

Please also generate and commit the JS bundles for the 2 PCIs:
```
cd tao/views/build
npm ci
npx grunt portableelement -e=pciSamples -i=textReaderInteraction
```

2024-07-03 14:30 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2024-07-04 07:15 UTC, oatymart approved these changes
Nice one, the extension seems fully working.

2024-07-05 08:12 UTC, merged